version: '3.3'

services:
  mysql:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: 'itcompany'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'