spring:
  datasource:
    url: 'jdbc:h2:mem:itcompany?useUnicode=yes&characterEncoding=UTF-8'
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mustache:
    suffix: '.html'
    prefix: 'classpath:/view/'

  mvc:
    static-path-pattern: '/resources/**'

logging.level.root: INFO
logging:
  path: './logs'
  file:
    max-history: 10